name: Publish Docker image to DockerHub
on:
  push:
    branches: [ master, fix/dockerfile ]
  pull_request:

jobs:
  docker:
    name: Build Docker Image and Publish (only on push)
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      # Steps required by docker/build-push-action@v2
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   if: github.event_name == 'push'
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      # - name: Build (always) and Publish (only on push)
      #   uses: docker/build-push-action@v2
      #   with:
      #     tags: ucbbar/chisel-bootcamp:latest
      #     push: ${{ github.event_name == 'push' }}
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --push \
            --tag your-username/multiarch-example:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .