name: Publish Docker image to DockerHub
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

# https://docs.docker.com/build/ci/github-actions/multi-platform/
jobs:
  docker:
    name: Build Docker Image and Publish (only on push)
    runs-on: ubuntu-latest
    steps:
      
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: sysprog21/chisel-bootcamp:latest