name: Publish Docker image
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  docker:
    name: Build Docker Image and Publish (only on push)
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      # Steps required by docker/build-push-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build (always) and Publish (only on push)
        uses: docker/build-push-action@v2
        with:
          tags: ucbbar/chisel-bootcamp:latest
          push: ${{ github.event_name == 'push' }}
