name: Publish Docker image
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  docker:
    name: Build Docker Image and Publish on Push
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      # Steps required by docker/build-push-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          tags: ucbbar/chisel-bootcamp:latest
          # TODO swap these before merge
          push: true
          #push: ${{ github.event_name == 'push' }}
